blog/urls.py
from django.urls import path

from . import views
from .views import AddPostView
app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('article/<int:pk>/', views.detail, name='detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    title_tag = models.CharField(max_length=20)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    # redirect page
    def get_absolute_url(self):
        return reverse('detail', args=(str(self.pk)))
        # return reverse('home')

blog/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import CreateView
from .models import Post


def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', {'posts': posts})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'detail.html', {'post': post})


class AddPostView(CreateView):
    model = Post
    template_name = 'add_post.html'
    fields = '__all__'

    def post(self, request):
        # do something
        return redirect(detail)

blog/templates/add_post.html
{% extends "base.html" %}

{% block title %}
create new post

{% endblock title %}

{% block content  %}

<h4>App Post</h4>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondary">add post </button>
    </form>
</div>

{% endblock content  %}

blog/templates/detail.html
{% extends "base.html" %}
{% block title %}
{{post.title_tag}}

{% endblock title %}

{% block content  %}
<h3>{{post.title}} </h3>
<small class="mb-5">
    by : {{post.author.first_name }} {{post.author.last_name }} - {{post.post_date}}
</small>

{{post.body|safe }}
<br>
<br>
<a class="btn btn-secondary" href="{% url 'blog:home' %}">back </a>

{% endblock content  %}

blog/templates/home.html
{% extends 'base.html' %}

{% block content  %}
<h4>Post Blog</h4>
{% for post in  posts %}

<li class="mb-4">
<li> <a href="{% url 'blog:detail' post.pk %}">{{post.title}}</a>
    {{post.author.first_name}} {{post.author.last_name}}-
    <br>
    {{post.body|slice:"200"|safe}}
</li>


{% endfor %}

{% endblock content  %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>
        {% block title %}
        My awesome cool blog
        {% endblock title %}
    </title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">My Awesome cool blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">





                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:add_post' %}">Add post</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Add category</a>
                </li>

            </ul>

        </div>
    </nav>
    <div class="container mt-5">

        {% block content  %}

        {% endblock content  %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>